/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#fef3e2',
          100: '#fde4b9',
          200: '#fbd38d',
          300: '#f9c35f',
          400: '#f7b735',
          500: '#f6ab00',
          600: '#e59d00',
          700: '#d08e00',
          800: '#bc7f00',
          900: '#9a6700',
        },
        secondary: {
          50: '#e8f5e9',
          100: '#c8e6c9',
          200: '#a5d6a7',
          300: '#81c784',
          400: '#66bb6a',
          500: '#4caf50',
          600: '#43a047',
          700: '#388e3c',
          800: '#2e7d32',
          900: '#1b5e20',
        },
        accent: {
          50: '#e3f2fd',
          100: '#bbdefb',
          200: '#90caf9',
          300: '#64b5f6',
          400: '#42a5f5',
          500: '#2196f3',
          600: '#1e88e5',
          700: '#1976d2',
          800: '#1565c0',
          900: '#0d47a1',
        },
        kid: {
          pink: '#ff6b9d',
          purple: '#c084fc',
          blue: '#60a5fa',
          green: '#4ade80',
          yellow: '#fbbf24',
          orange: '#fb923c',
          red: '#f87171',
        },
        admin: {
          primary: 'var(--admin-primary)',
          'primary-strong': 'var(--admin-primary-strong)',
          surface: 'var(--admin-surface)',
          'surface-muted': 'var(--admin-surface-muted)',
          border: 'var(--admin-border)',
          'border-accent': 'var(--admin-border-accent)',
          text: 'var(--admin-text)',
          'text-muted': 'var(--admin-text-muted)',
          success: 'var(--admin-success)',
          warning: 'var(--admin-warning)',
          danger: 'var(--admin-danger)',
          info: 'var(--admin-info)',
        },
      },
      fontFamily: {
        comic: ['Comic Neue', 'Comic Sans MS', 'cursive'],
        rounded: ['Nunito', 'Varela Round', 'sans-serif'],
      },
      borderRadius: {
        'xl': '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
      },
      boxShadow: {
        'kid': '0 4px 20px rgba(0, 0, 0, 0.1), 0 2px 8px rgba(0, 0, 0, 0.08)',
        'kid-lg': '0 8px 30px rgba(0, 0, 0, 0.12), 0 4px 12px rgba(0, 0, 0, 0.1)',
        'kid-hover': '0 12px 40px rgba(0, 0, 0, 0.15), 0 6px 16px rgba(0, 0, 0, 0.12)',
        'admin-sm': 'var(--admin-shadow-sm)',
        'admin-md': 'var(--admin-shadow-md)',
        'admin-lg': 'var(--admin-shadow-lg)',
      },
      animation: {
        'bounce-slow': 'bounce 2s infinite',
        'pulse-slow': 'pulse 3s infinite',
        'wiggle': 'wiggle 0.5s ease-in-out',
        'pop': 'pop 0.3s ease-out',
        'star-spin': 'star-spin 1s ease-in-out',
      },
      keyframes: {
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        pop: {
          '0%': { transform: 'scale(0.8)', opacity: '0' },
          '50%': { transform: 'scale(1.1)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'star-spin': {
          '0%': { transform: 'rotate(0deg) scale(0)' },
          '50%': { transform: 'rotate(180deg) scale(1.2)' },
          '100%': { transform: 'rotate(360deg) scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
